### ISSUE TITLE
Numpy incompatibility 

### ISSUE THREAD

**Issue by elupus** [tiagocoutinho/async_modbus#15]
* Async ModBus version: 0.2.1
* Python version: 3.12
* Operating System: Linux

### Description

Module is incompatible with newer numpy versions due to changes in numpy behaviour.

https://github.com/home-assistant/core/issues/132347

### What I Did

```
Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:526
First occurred: 8:54:48 AM (2 occurrences)
Last logged: 8:55:12 AM

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Unable to avoid copy while creating an array as requested. If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x). For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 122, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/usr/src/homeassistant/homeassistant/components/nibe_heatpump/number.py", line 77, in async_set_native_value
    await self._async_write_coil(value)
  File "/usr/src/homeassistant/homeassistant/components/nibe_heatpump/entity.py", line 44, in _async_write_coil
    await self.coordinator.async_write_coil(self._coil, value)
  File "/usr/src/homeassistant/homeassistant/components/nibe_heatpump/coordinator.py", line 132, in async_write_coil
    await self.connection.write_coil(data)
  File "/usr/local/lib/python3.13/site-packages/tenacity/asyncio/__init__.py", line 189, in async_wrapped
    return await copy(fn, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/tenacity/asyncio/__init__.py", line 111, in __call__
    do = await self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/tenacity/asyncio/__init__.py", line 153, in iter
    result = await action(retry_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/tenacity/_utils.py", line 99, in inner
    return call(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.13/site-packages/tenacity/asyncio/__init__.py", line 114, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/nibe/connection/modbus.py", line 142, in write_coil
    result = await self._client.write_registers(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/async_modbus/core.py", line 233, in write_registers
    request = self.protocol.write_multiple_registers(
        slave_id, starting_address, values
    )
  File "/usr/local/lib/python3.13/site-packages/umodbus/client/tcp.py", line 223, in write_multiple_registers
    return _create_request_adu(slave_id, function.request_pdu)
                                         ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/async_modbus/umodbus_numpy.py", line 130, in request_pdu_registers
    return pack_16bits(self.function_code, self.starting_address, self._values)
  File "/usr/local/lib/python3.13/site-packages/async_modbus/umodbus_numpy.py", line 46, in pack_16bits
    values = numpy.array(values, dtype=dtype, copy=False)
ValueError: Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.
```

**Comment by storeman** [comment]
I'm not used to Python, but I managed to run the tests successfully with this fix in a docker container on Python 3.10. Created a PR.

**Comment by liquidblack** [comment]
> I'm not used to Python, but I managed to run the tests successfully with this fix in a docker container on Python 3.10. Created a PR.

That was the blocker for me doing this: getting a working test environment. Nice work @storeman this will help those few of us playing with modbus and nibe - thanks!

**Comment by tiagocoutinho** [comment]
Thanks for the PR @storeman 
I just have one comment. Otherwise looks good.

**Comment by storeman** [comment]
Thanks @tiagocoutinho. Any chance you can release this fix soon?

**Comment by tiagocoutinho** [comment]
Sure, latest 0.2.2 on pypi should contain the fix

**Comment by elupus** [comment]
Seems release is missing on github https://github.com/tiagocoutinho/async_modbus/releases but i do see it on pypi and do see a tag. So mostly fine.

**Comment by jowi1968** [comment]
When will this be available in e.g. Home Assistant?

**Comment by tiagocoutinho** [comment]
@elupus , i don't cut github releases for this project. I don't want to be too tied to github. Is pypi package and git tag enough for you?
